FROM node:7

EXPOSE 8080
EXPOSE 3000

WORKDIR /app

COPY package.json package.json

RUN npm install
ENV LOCAL_ENV=dev

#Command will only work if you mount the git folder under /app
CMD npm run start
