version: '2'

services:
  gui:
    image: huygensing/elab-pub-boschdoc:builbase
    build: 
      dockerfile: Dockerfile.buildbase
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes: 
      - .:/app
